#ifndef SYS_HW_DEF_H_
#define SYS_HW_DEF_H_

#include "gpio_class.h"

// 四参数电源
#define FOUR_PARAM_PW_GOIO_DEF { GPIO_TYPE_WRITE, GPIO_PIN_HIGH, {GPIO_PIN_0, GPIOA} }

// 水泵电源
#define PUMP_PW_GOIO_DEF { GPIO_TYPE_WRITE, GPIO_PIN_HIGH, {GPIO_PIN_1, GPIOA} }

// 五参数电源
#define FIVE_PARAM_PW_GOIO_DEF { GPIO_TYPE_WRITE, GPIO_PIN_HIGH, {GPIO_PIN_2, GPIOA} }

// 进水阀电源
#define WATER_IN_VALVE_PW_GPIO_DEF { GPIO_TYPE_WRITE, GPIO_PIN_HIGH, {GPIO_PIN_3, GPIOA} }

// 排水阀电源
#define WATER_OUT_VALVE_PW_GPIO_DEF { GPIO_TYPE_WRITE, GPIO_PIN_HIGH, {GPIO_PIN_9, GPIOE} }

// 绞盘机电源
#define MOTOR_PW_GPIO_DEF { GPIO_TYPE_WRITE, GPIO_PIN_HIGH, {GPIO_PIN_11, GPIOE} }

// 信号灯1
#define LED1_PW_GPIO_DEF { GPIO_TYPE_WRITE, GPIO_PIN_HIGH, {GPIO_PIN_13, GPIOE} }

// 信号灯2
#define LED2_PW_GPIO_DEF { GPIO_TYPE_WRITE, GPIO_PIN_HIGH, {GPIO_PIN_14, GPIOE} }

// 保留1
#define REC1_GPIO_DEF { GPIO_TYPE_WRITE, GPIO_PIN_HIGH, {GPIO_PIN_7, GPIOD} }

// 保留2
#define REC2_GPIO_DEF { GPIO_TYPE_WRITE, GPIO_PIN_HIGH, {GPIO_PIN_3, GPIOB} }

// 液位开关1
#define LEVEL_SW1_IN_GPIO_DEF { GPIO_TYPE_READ, GPIO_PIN_HIGH, {GPIO_PIN_0, GPIOB} }

// 液位开关2
#define LEVEL_SW2_IN_GPIO_DEF { GPIO_TYPE_READ, GPIO_PIN_HIGH, {GPIO_PIN_5, GPIOC} }

// 金属感应器1输入
#define METAL_SW1_GPIO_DEF { GPIO_TYPE_READ, GPIO_PIN_HIGH, {GPIO_PIN_4, GPIOC} }

// 金属感应器2输入
#define METAL_SW2_GPIO_DEF { GPIO_TYPE_READ, GPIO_PIN_HIGH, {GPIO_PIN_7, GPIOA} }

// 金属感应器3输入
#define METAL_SW3_GPIO_DEF { GPIO_TYPE_READ, GPIO_PIN_HIGH, {GPIO_PIN_6, GPIOA} }

// 金属感应器4输入
#define METAL_SW4_GPIO_DEF { GPIO_TYPE_READ, GPIO_PIN_HIGH, {GPIO_PIN_5, GPIOA} }

// 金属感应器5输入
#define METAL_SW5_GPIO_DEF { GPIO_TYPE_READ, GPIO_PIN_HIGH, {GPIO_PIN_4, GPIOA} }

// 信号1输出
#define SIGNAL1_OUT_GPIO_DEF { GPIO_TYPE_READ, GPIO_PIN_HIGH, {GPIO_PIN_1, GPIOE} }

// 信号2输出
#define SIGNAL2_OUT_GPIO_DEF { GPIO_TYPE_READ, GPIO_PIN_HIGH, {GPIO_PIN_0, GPIOE} }

// 信号3输出
#define SIGNAL3_OUT_GPIO_DEF { GPIO_TYPE_READ, GPIO_PIN_HIGH, {GPIO_PIN_9, GPIOB} }

// 信号4输出
#define SIGNAL4_OUT_GPIO_DEF { GPIO_TYPE_READ, GPIO_PIN_HIGH, {GPIO_PIN_8, GPIOB} }

// 信号5输出
#define SIGNAL5_OUT_GPIO_DEF { GPIO_TYPE_READ, GPIO_PIN_HIGH, {GPIO_PIN_5, GPIOB} }

// 信号6输出
#define SIGNAL6_OUT_GPIO_DEF { GPIO_TYPE_READ, GPIO_PIN_HIGH, {GPIO_PIN_11, GPIOB} }

// 信号7输出
#define SIGNAL7_OUT_GPIO_DEF { GPIO_TYPE_READ, GPIO_PIN_HIGH, {GPIO_PIN_6, GPIOE} }

// 信号8输出
#define SIGNAL8_OUT_GPIO_DEF { GPIO_TYPE_READ, GPIO_PIN_HIGH, {GPIO_PIN_5, GPIOE} }

// 信号9输出
#define SIGNAL9_OUT_GPIO_DEF { GPIO_TYPE_READ, GPIO_PIN_HIGH, {GPIO_PIN_4, GPIOE} }

// 信号10输出
#define SIGNAL10_OUT_GPIO_DEF { GPIO_TYPE_READ, GPIO_PIN_HIGH, {GPIO_PIN_3, GPIOE} }

// 信号11输出
#define SIGNAL11_OUT_GPIO_DEF { GPIO_TYPE_READ, GPIO_PIN_HIGH, {GPIO_PIN_4, GPIOD} }

// 信号12输出
#define SIGNAL12_OUT_GPIO_DEF { GPIO_TYPE_READ, GPIO_PIN_HIGH, {GPIO_PIN_3, GPIOD} }

#endif
